user:
    admin: [albertinizao@gmail.com]
    
spring:
    data:
        mongodb:
            uri: mongodb://root:root@ds139869.mlab.com:39869/heroku_3kspc207
     
security:
    basic:
        enabled: false
            
token:
    secret: 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==